// @loom/deployment — the Loom wallet deployment toolkit.
//
// One reusable path from "forge script --broadcast" to an application that can
// trust its configuration: parse the broadcast, read live bytecode from the
// chain, compute code hashes locally, write a versioned manifest plus env
// values, then re-read everything and verify env == manifest == chain. Every
// mismatch fails closed. Node-only tooling — never import this from an app's
// runtime bundle.

import crypto from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { dirname, join, relative } from "node:path";
import jsSha3 from "js-sha3";

const { keccak256 } = jsSha3;

/** Versioned manifest schema; bump on breaking manifest shape changes. */
export const MANIFEST_SCHEMA_VERSION = 1;

export const DEFAULT_CONTRACTS = Object.freeze({
  accountFactory: "LoomAccountFactory",
  passkeyValidator: "P256Validator",
  accountImplementation: "LoomAccount"
});

export const NATIVE_P256_PRECOMPILE = "0x0000000000000000000000000000000000000100";

export function parseFoundryBroadcast(broadcast, options = {}) {
  assertObject(broadcast, "broadcast");
  const contracts = { ...DEFAULT_CONTRACTS, ...(options.contracts ?? {}) };
  const created = new Map();

  const transactionHashes = new Map();
  for (const tx of broadcast.transactions ?? []) {
    if (tx?.transactionType === "CREATE" && tx.contractName && tx.contractAddress) {
      created.set(tx.contractName, requireAddress(tx.contractAddress, `CREATE ${tx.contractName}`));
      if (typeof tx.hash === "string") transactionHashes.set(tx.contractName, tx.hash);
    }
    for (const contract of tx?.additionalContracts ?? []) {
      if (contract.contractName && contract.address) {
        created.set(contract.contractName, requireAddress(contract.address, `additional ${contract.contractName}`));
        if (typeof tx?.hash === "string") transactionHashes.set(contract.contractName, tx.hash);
      }
    }
  }

  const addressFor = label => {
    const contractName = contracts[label];
    const address = created.get(contractName);
    if (!address) throw new Error(`broadcast has no deployed ${contractName}`);
    return address;
  };

  return Object.freeze({
    chainId: Number(broadcast.chain),
    sourceCommit: typeof broadcast.commit === "string" ? broadcast.commit : undefined,
    addresses: Object.freeze({
      accountFactory: addressFor("accountFactory"),
      passkeyValidator: addressFor("passkeyValidator"),
      accountImplementation: addressFor("accountImplementation")
    }),
    createdContracts: Object.freeze(Object.fromEntries(created)),
    transactionHashes: Object.freeze(Object.fromEntries(transactionHashes))
  });
}

export async function buildWalletDeploymentManifest(options) {
  assertObject(options, "options");
  const parsed = parseFoundryBroadcast(options.broadcast, options);
  const rpc = requireFunction(options.rpc, "options.rpc");
  const entryPoint = requireAddress(options.entryPoint, "entryPoint");
  const p256VerifierMode = options.p256VerifierMode ?? "native-precompile";
  if (p256VerifierMode !== "native-precompile" && p256VerifierMode !== "fallback-contract") {
    throw new Error("p256VerifierMode must be native-precompile or fallback-contract");
  }
  const p256Verifier = requireAddress(
    options.p256Verifier ?? (p256VerifierMode === "native-precompile" ? NATIVE_P256_PRECOMPILE : undefined),
    "p256Verifier"
  );

  const codehashes = {
    accountFactory: await codehash(rpc, parsed.addresses.accountFactory, "LoomAccountFactory"),
    passkeyValidator: await codehash(rpc, parsed.addresses.passkeyValidator, "P256Validator"),
    accountImplementation: await codehash(rpc, parsed.addresses.accountImplementation, "LoomAccount")
  };
  await codehash(rpc, entryPoint, "EntryPoint");
  if (p256VerifierMode === "fallback-contract") {
    codehashes.p256Verifier = await codehash(rpc, p256Verifier, "P-256 fallback verifier");
  }

  if (p256VerifierMode === "native-precompile") {
    const probe = await requireFunction(options.probeP256, "options.probeP256")();
    if (!probe?.supported) throw new Error("native P-256 precompile probe failed");
  }

  return Object.freeze({
    schemaVersion: MANIFEST_SCHEMA_VERSION,
    chainId: parsed.chainId,
    deployedAt: options.deployedAt ?? new Date().toISOString(),
    sourceCommit: parsed.sourceCommit ?? null,
    entryPoint,
    accountFactory: parsed.addresses.accountFactory,
    passkeyValidator: parsed.addresses.passkeyValidator,
    p256Verifier,
    p256VerifierMode,
    codehashes: Object.freeze(codehashes),
    deploymentBlock: options.deploymentBlock ?? null,
    notes: options.notes ?? "Generated by Loom deployment tooling."
  });
}

export function envForWalletDeployment(manifest, manifestReference) {
  assertObject(manifest, "manifest");
  return Object.freeze({
    EXPO_PUBLIC_LOOM_CHAIN_ID: String(requirePositiveInteger(manifest.chainId, "manifest.chainId")),
    EXPO_PUBLIC_LOOM_L1_CHAIN_ID: String(manifest.chainId),
    EXPO_PUBLIC_LOOM_ENTRYPOINT: requireAddress(manifest.entryPoint, "manifest.entryPoint"),
    EXPO_PUBLIC_LOOM_ACCOUNT_FACTORY: requireAddress(manifest.accountFactory, "manifest.accountFactory"),
    EXPO_PUBLIC_LOOM_PASSKEY_VALIDATOR: requireAddress(manifest.passkeyValidator, "manifest.passkeyValidator"),
    EXPO_PUBLIC_LOOM_P256_VERIFIER_MODE: requireMode(manifest.p256VerifierMode),
    EXPO_PUBLIC_LOOM_P256_VERIFIER: requireAddress(manifest.p256Verifier, "manifest.p256Verifier"),
    EXPO_PUBLIC_LOOM_DEPLOYMENT_MANIFEST: requireString(manifestReference, "manifestReference")
  });
}

export async function writeWalletDeploymentFiles(options) {
  assertObject(options, "options");
  const manifest = assertObject(options.manifest, "options.manifest");
  const manifestPath = requireString(options.manifestPath, "options.manifestPath");
  const envPath = requireString(options.envPath, "options.envPath");
  const manifestReference = requireString(options.manifestReference, "options.manifestReference");
  const envUpdates = envForWalletDeployment(manifest, manifestReference);

  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  const envText = existsSync(envPath) ? await readFile(envPath, "utf8") : "";
  await writeFile(envPath, updateEnv(envText, envUpdates));
  return Object.freeze({ manifestPath, envPath, envUpdates });
}

export async function verifyWalletDeploymentFiles(options) {
  assertObject(options, "options");
  const manifest = JSON.parse(await readFile(requireString(options.manifestPath, "options.manifestPath"), "utf8"));
  const env = parseEnv(await readFile(requireString(options.envPath, "options.envPath"), "utf8"));
  const rpc = requireFunction(options.rpc, "options.rpc");
  const checks = [];
  const add = (label, ok, detail = "") => checks.push(Object.freeze({ label, ok, detail }));
  const same = (a, b) => String(a).toLowerCase() === String(b).toLowerCase();

  add("env chainId == manifest chainId", same(env.EXPO_PUBLIC_LOOM_CHAIN_ID, manifest.chainId));
  add("env l1ChainId == manifest chainId", same(env.EXPO_PUBLIC_LOOM_L1_CHAIN_ID, manifest.chainId));
  add("env entryPoint == manifest", same(env.EXPO_PUBLIC_LOOM_ENTRYPOINT, manifest.entryPoint));
  add("env factory == manifest", same(env.EXPO_PUBLIC_LOOM_ACCOUNT_FACTORY, manifest.accountFactory));
  add("env passkeyValidator == manifest", same(env.EXPO_PUBLIC_LOOM_PASSKEY_VALIDATOR, manifest.passkeyValidator));
  add("env p256Verifier == manifest", same(env.EXPO_PUBLIC_LOOM_P256_VERIFIER, manifest.p256Verifier));
  add("env p256 mode == manifest", same(env.EXPO_PUBLIC_LOOM_P256_VERIFIER_MODE, manifest.p256VerifierMode));

  const codeAddress = {
    accountFactory: manifest.accountFactory,
    passkeyValidator: manifest.passkeyValidator,
    accountImplementation: options.accountImplementation,
    p256Verifier: manifest.p256Verifier
  };
  for (const [name, expected] of Object.entries(manifest.codehashes ?? {})) {
    const address = requireAddress(codeAddress[name], `address for ${name}`);
    const fresh = await codehash(rpc, address, name);
    add(`chain codehash(${name}) == manifest`, same(fresh, expected), address);
  }

  if (manifest.p256VerifierMode === "native-precompile") {
    const probe = await requireFunction(options.probeP256, "options.probeP256")();
    add("native P-256 precompile verifies a live test vector", probe?.supported === true, manifest.p256Verifier);
  }

  const failures = checks.filter(check => !check.ok);
  return Object.freeze({ manifest: Object.freeze(manifest), env: Object.freeze(env), checks: Object.freeze(checks), failures });
}

export async function connectWalletAppDeployment(options) {
  const broadcastPath = requireString(options.broadcastPath, "options.broadcastPath");
  const broadcast = JSON.parse(await readFile(broadcastPath, "utf8"));
  const parsed = parseFoundryBroadcast(broadcast, options);
  const manifest = await buildWalletDeploymentManifest({
    ...options,
    broadcast,
    notes:
      options.notes ??
      `Generated by Loom deployment tooling from ${relative(dirname(options.manifestPath), broadcastPath)}`
  });
  await writeWalletDeploymentFiles({ ...options, manifest });
  const verification = await verifyWalletDeploymentFiles({
    ...options,
    accountImplementation: parsed.addresses.accountImplementation
  });
  if (verification.failures.length !== 0) {
    throw new Error(`${verification.failures.length} deployment verification check(s) failed`);
  }
  return Object.freeze({ manifest, verification, parsed });
}

export function createJsonRpcClient(rpcUrl) {
  requireString(rpcUrl, "rpcUrl");
  return async function rpc(method, params) {
    const response = await fetch(rpcUrl, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params })
    });
    const body = await response.json();
    if (body.error) throw new Error(`${method}: ${body.error.message}`);
    return body.result;
  };
}

function updateEnv(source, updates) {
  let env = source;
  for (const [key, value] of Object.entries(updates)) {
    const line = `${key}=${value}`;
    env = new RegExp(`^${key}=`, "m").test(env)
      ? env.replace(new RegExp(`^${key}=.*$`, "m"), line)
      : `${env.trimEnd()}\n${line}\n`;
  }
  return env;
}

function parseEnv(source) {
  return Object.freeze(Object.fromEntries(
    source
      .split(/\r?\n/)
      .filter(line => line.includes("=") && !line.trim().startsWith("#"))
      .map(line => [line.slice(0, line.indexOf("=")).trim(), line.slice(line.indexOf("=") + 1).trim()])
  ));
}

async function codehash(rpc, address, label) {
  const code = await rpc("eth_getCode", [requireAddress(address, label), "latest"]);
  if (!code || code === "0x") throw new Error(`${label} at ${address} has no code on chain`);
  if (!/^0x[0-9a-fA-F]*$/u.test(code)) throw new Error(`${label} returned non-hex code`);
  return `0x${keccak256(Buffer.from(code.slice(2), "hex"))}`;
}

function requireMode(value) {
  if (value !== "native-precompile" && value !== "fallback-contract") {
    throw new Error("p256VerifierMode must be native-precompile or fallback-contract");
  }
  return value;
}

function requireAddress(value, label) {
  if (typeof value !== "string" || !/^0x[0-9a-fA-F]{40}$/u.test(value)) {
    throw new Error(`${label} must be a 20-byte address`);
  }
  return value;
}

function requirePositiveInteger(value, label) {
  if (!Number.isSafeInteger(value) || value <= 0) throw new Error(`${label} must be a positive integer`);
  return value;
}

function requireString(value, label) {
  if (!value || typeof value !== "string") throw new Error(`${label} is required`);
  return value;
}

function requireFunction(value, label) {
  if (typeof value !== "function") throw new Error(`${label} is required`);
  return value;
}

function assertObject(value, label) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`);
  return value;
}

// ---------------------------------------------------------------------------
// Native P-256 precompile probe (EIP-7951).
//
// Signs a fresh P-256 vector with a throwaway software key and asks the
// precompile at 0x100 to verify it via eth_call. A functioning precompile
// returns 32-byte 0x…01 for the valid signature and empty output for a
// corrupted one; anything else means native mode must not be used.
// ---------------------------------------------------------------------------

export async function probeP256Precompile(rpc) {
  const call = requireFunction(rpc, "rpc");
  const { privateKey, publicKey } = crypto.generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  const message = crypto.randomBytes(64);
  const hash = crypto.createHash("sha256").update(message).digest();
  const derSig = crypto.sign("sha256", message, { key: privateKey, dsaEncoding: "der" });
  const jwk = publicKey.export({ format: "jwk" });
  const input =
    "0x" +
    Buffer.concat([
      hash,
      derSignatureToRs(derSig),
      Buffer.from(jwk.x, "base64url"),
      Buffer.from(jwk.y, "base64url")
    ]).toString("hex");

  const valid = await call("eth_call", [{ to: NATIVE_P256_PRECOMPILE, data: input }, "latest"]);
  const corrupted = input.slice(0, 2 + 64) + (input[2 + 64] === "a" ? "b" : "a") + input.slice(2 + 65);
  const invalid = await call("eth_call", [{ to: NATIVE_P256_PRECOMPILE, data: corrupted }, "latest"]);

  return Object.freeze({
    supported:
      valid === "0x0000000000000000000000000000000000000000000000000000000000000001" &&
      (invalid === "0x" || invalid === null),
    valid,
    invalid
  });
}

function derSignatureToRs(der) {
  let i = 2;
  if (der[1] & 0x80) i += der[1] & 0x7f;
  i += 1;
  const rLength = der[i];
  i += 1;
  const r = der.slice(i, i + rLength);
  i += rLength;
  i += 1;
  const sLength = der[i];
  i += 1;
  const s = der.slice(i, i + sLength);
  const pad = bytes => {
    let b = Buffer.from(bytes);
    while (b.length > 32) b = b.slice(1);
    while (b.length < 32) b = Buffer.concat([Buffer.alloc(1), b]);
    return b;
  };
  return Buffer.concat([pad(r), pad(s)]);
}

// ---------------------------------------------------------------------------
// Foundry deployment runner.
//
// Spawns `forge script <script> --rpc-url <url> --broadcast` with the given
// environment and resolves with the broadcast path. The runner never parses
// forge's stdout — the broadcast JSON is the machine-readable source of truth.
// ---------------------------------------------------------------------------

export async function runFoundryDeployment(options) {
  assertObject(options, "options");
  const repoRoot = requireString(options.repoRoot, "options.repoRoot");
  const script = requireString(options.script, "options.script");
  const rpcUrl = requireString(options.rpcUrl, "options.rpcUrl");
  const scriptFile = script.includes(":") ? script.slice(0, script.indexOf(":")) : script;
  const scriptName = scriptFile.split("/").pop().replace(/\.s\.sol$/u, ".s.sol");

  const forgeBin =
    options.forgeBin ??
    [join(repoRoot, "node_modules", "@foundry-rs", "forge-win32-amd64", "bin", "forge.exe")].find(existsSync) ??
    "forge";
  const spawnImpl = options.spawn ?? spawn;

  const exitCode = await new Promise((resolve, reject) => {
    const child = spawnImpl(forgeBin, ["script", script, "--rpc-url", rpcUrl, "--broadcast", ...(options.extraArgs ?? [])], {
      cwd: repoRoot,
      stdio: options.stdio ?? "inherit",
      env: { ...process.env, ...(options.env ?? {}) }
    });
    child.on("error", reject);
    child.on("exit", code => resolve(code ?? 1));
  });
  if (exitCode !== 0) {
    throw new Error(`forge deployment exited with code ${exitCode}; nothing was connected`);
  }

  const chainId = requirePositiveInteger(options.chainId, "options.chainId");
  const broadcastPath = join(repoRoot, "broadcast", scriptName, String(chainId), "run-latest.json");
  if (!existsSync(broadcastPath)) {
    throw new Error(`forge reported success but the broadcast is missing: ${broadcastPath}`);
  }
  return Object.freeze({ broadcastPath, forgeBin });
}

// ---------------------------------------------------------------------------
// Per-network deployment records (deployments/<chainId>.json).
//
// The registry pattern used across the ecosystem (hardhat-deploy, Ignition's
// deployed_addresses.json): one JSON file per network mapping contract names
// to addresses plus provenance, so other tooling can consume a deployment
// without re-parsing forge broadcasts.
// ---------------------------------------------------------------------------

export async function saveDeploymentRecord(options) {
  assertObject(options, "options");
  const directory = requireString(options.directory, "options.directory");
  const manifest = assertObject(options.manifest, "options.manifest");
  const parsed = assertObject(options.parsed, "options.parsed");
  const record = Object.freeze({
    schemaVersion: MANIFEST_SCHEMA_VERSION,
    chainId: requirePositiveInteger(manifest.chainId, "manifest.chainId"),
    deployedAt: manifest.deployedAt ?? null,
    sourceCommit: manifest.sourceCommit ?? null,
    contracts: parsed.createdContracts,
    transactionHashes: parsed.transactionHashes ?? {},
    manifest
  });
  await mkdir(directory, { recursive: true });
  const recordPath = join(directory, `${record.chainId}.json`);
  await writeFile(recordPath, `${JSON.stringify(record, null, 2)}\n`);
  return Object.freeze({ recordPath, record });
}

export async function loadDeploymentRecord(options) {
  assertObject(options, "options");
  const recordPath = join(
    requireString(options.directory, "options.directory"),
    `${requirePositiveInteger(options.chainId, "options.chainId")}.json`
  );
  if (!existsSync(recordPath)) return undefined;
  const record = JSON.parse(await readFile(recordPath, "utf8"));
  if (record.schemaVersion !== MANIFEST_SCHEMA_VERSION) {
    throw new Error(
      `deployment record ${recordPath} uses schema ${record.schemaVersion}; this toolkit expects ${MANIFEST_SCHEMA_VERSION}`
    );
  }
  return record;
}

// ---------------------------------------------------------------------------
// Full pipeline: deploy -> connect -> verify -> record.
// ---------------------------------------------------------------------------

export async function deployAndConnectWallet(options) {
  assertObject(options, "options");
  const rpc = options.rpc ?? createJsonRpcClient(requireString(options.rpcUrl, "options.rpcUrl"));
  const probeP256 = options.probeP256 ?? (() => probeP256Precompile(rpc));

  const { broadcastPath } = await runFoundryDeployment(options);
  const connected = await connectWalletAppDeployment({
    ...options,
    broadcastPath,
    rpc,
    probeP256
  });
  let recordPath;
  if (options.recordDirectory) {
    ({ recordPath } = await saveDeploymentRecord({
      directory: options.recordDirectory,
      manifest: connected.manifest,
      parsed: connected.parsed
    }));
  }
  return Object.freeze({ ...connected, broadcastPath, recordPath });
}

// ---------------------------------------------------------------------------
// Deployment gas report.
//
// Extracts the real gas each contract deployment cost from a Foundry
// broadcast: every CREATE transaction matched to its receipt by transaction
// hash, so ordering assumptions cannot silently misattribute gas. gasUsed is
// the computational cost and is identical for the same bytecode on any chain,
// so a devnet run reports the same per-contract deployment gas as mainnet.
// ---------------------------------------------------------------------------

export function deploymentGasReport(broadcast, options = {}) {
  assertObject(broadcast, "broadcast");
  const exclude = new Set(options.exclude ?? []);
  const gasByHash = new Map();
  for (const receipt of broadcast.receipts ?? []) {
    if (receipt?.transactionHash && receipt.gasUsed) {
      gasByHash.set(receipt.transactionHash.toLowerCase(), BigInt(receipt.gasUsed));
    }
  }

  const contracts = [];
  let totalGas = 0n;
  for (const tx of broadcast.transactions ?? []) {
    if (tx?.transactionType !== "CREATE" || !tx.contractName || exclude.has(tx.contractName)) continue;
    const gas = tx.hash ? gasByHash.get(tx.hash.toLowerCase()) : undefined;
    if (gas === undefined) continue;
    totalGas += gas;
    contracts.push(
      Object.freeze({ contractName: tx.contractName, address: tx.contractAddress ?? null, gasUsed: Number(gas) })
    );
  }
  return Object.freeze({ contracts: Object.freeze(contracts), totalGas: Number(totalGas) });
}
