import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const uiRoot = new URL("../ui/", import.meta.url);

test("Wallet Lab presents wallet evidence as a plain-language journey", () => {
  const html = readFileSync(new URL("index.html", uiRoot), "utf8");
  const script = readFileSync(new URL("app.js", uiRoot), "utf8");

  for (const panel of ["architecture", "operations", "network", "evm"]) {
    assert.match(html, new RegExp(`id="tab-${panel}"[^>]+role="tab"|role="tab"[^>]+id="tab-${panel}"`, "u"));
    assert.match(html, new RegExp(`id="panel-${panel}"[^>]+role="tabpanel"|role="tabpanel"[^>]+id="panel-${panel}"`, "u"));
  }
  assert.match(html, /<script type="module" src="\/app\.js"><\/script>/u);
  assert.doesNotMatch(html, /<script(?![^>]+src=)/u);
  for (const removed of ["tab-overview", "tab-timeline", "tab-userop", "tab-webauthn"]) assert.doesNotMatch(html, new RegExp(`id="${removed}"`, "u"));
  assert.match(html, /Choose an inspection target/u);
  assert.match(html, /active-deployment-name/u);
  assert.match(html, /metric-result-context/u);
  assert.match(html, /metric-network/u);
  assert.match(html, /metric-checks-context/u);
  assert.match(html, /metric-duration-context/u);
  assert.doesNotMatch(html, /<span>Result<\/span>/u);
  assert.doesNotMatch(html, /<select id="deployment-source"/u);
  assert.match(html, /Local deterministic deployment/u);
  assert.match(html, /Connect Sepolia deployment/u);
  assert.match(html, /sepolia-provider/u);
  assert.match(html, /System architecture/u);
  assert.match(html, /account-model-explainer/u);
  assert.match(html, /contract-dossier/u);
  assert.match(html, /abi-groups/u);
  assert.match(html, /architecture-browser/u);
  assert.match(html, /id="execution-workspace"/u);
  assert.doesNotMatch(html, /DEPLOYED CODE/u);
  assert.doesNotMatch(html, /id="contract-search"/u);
  assert.doesNotMatch(html, /id="contract-list"/u);
  assert.match(html, /graph-zoom-in/u);
  assert.match(html, /graph-reset-view/u);
  assert.match(html, /trace-overlay-toggle/u);
  assert.match(html, /Static architecture/u);
  assert.match(html, /Observed operations/u);
  assert.match(html, /RPC by operation/u);
  assert.match(html, /All technical stages/u);
  assert.doesNotMatch(html, /<details open[^>]*>\s*<summary>Technical details/u);
  assert.match(script, /function renderJourney\(/u);
  assert.match(script, /function renderOperation\(/u);
  assert.match(script, /function renderPasskeyProof\(/u);
  assert.match(script, /function renderNetwork\(/u);
  assert.match(script, /function renderOperationMap\(/u);
  assert.match(script, /function renderArchitectureSummary\(/u);
  assert.match(script, /function renderAccountModelExplainer\(/u);
  assert.match(script, /function runOutcomeLabel\(/u);
  assert.match(script, /function networkLabel\(/u);
  assert.doesNotMatch(script, /does not include both an implementation and an observed account instance/u);
  assert.match(script, /function renderContractDossier\(/u);
  assert.match(script, /function githubSourceUrl\(/u);
  assert.match(script, /source\?\.upstream\?\.repository/u);
  assert.match(script, /github\.com\/\$\{source\.upstream\.repository\}\/blob/u);
  assert.match(script, /function explorerAddressUrl\(/u);
  assert.match(script, /View on Sepolia Blockscout/u);
  assert.match(script, /Local chain address/u);
  assert.match(script, /Open source on GitHub/u);
  assert.match(script, /<details class="dossier-metadata">/u);
  assert.match(script, /Contract metadata/u);
  assert.doesNotMatch(script, /Why runtime code matters/u);
  assert.doesNotMatch(script, /Runtime code commitment/u);
  assert.match(script, /Repository path pinned to the commit recorded by this run/u);
  assert.match(script, /function renderAbiGroups\(/u);
  assert.match(script, /function renderFunctionInteractions\(/u);
  assert.match(script, /Why this function exists/u);
  assert.match(script, /Resolved value/u);
  assert.match(script, /Declared expression/u);
  assert.doesNotMatch(script, /Declared fields/u);
  assert.match(script, /function-purpose/u);
  assert.match(script, /function artifactRevision\(/u);
  assert.match(script, /function captureOpenDetails\(/u);
  assert.match(script, /function restoreOpenDetails\(/u);
  assert.match(script, /if \(revision !== state\.artifactRevision\)/u);
  assert.match(script, /function observedTraceOverlay\(/u);
  assert.match(script, /function renderSourceExcerpt\(/u);
  assert.doesNotMatch(script, /Evidence provenance/u);
  assert.match(script, /function beginGraphInteraction\(/u);
  assert.match(script, /function moveGraphInteraction\(/u);
  assert.match(script, /function selectArchitectureContract\(/u);
  assert.match(script, /interaction\.type === "node"/u);
  assert.match(script, /function connectSepoliaDeployment\(/u);
  assert.match(script, /function showDeploymentWorkspace\(/u);
  assert.match(script, /function renderDeployment\(/u);
  assert.match(script, /function renderFunctionInspector\(/u);
  assert.match(script, /function renderExecutionWorkspace\(/u);
  const functionInspectorSource = script.slice(script.indexOf("function renderFunctionInspector("), script.indexOf("function renderExecutionWorkspace("));
  const executionWorkspaceSource = script.slice(script.indexOf("function renderExecutionWorkspace("), script.indexOf("function traceBigInt("));
  assert.doesNotMatch(functionInspectorSource, /HYPOTHETICAL INPUT/u);
  assert.match(executionWorkspaceSource, /HYPOTHETICAL INPUT/u);
  assert.match(executionWorkspaceSource, /Contract calls, EVM frames, and bounded opcode evidence/u);
  assert.match(script, /function runExecutionSimulation\(/u);
  assert.match(script, /function runLocalExecution\(/u);
  assert.match(script, /function sendSepoliaExecution\(/u);
  assert.match(script, /freshSimulation/u);
  assert.match(script, /from: accounts\[0\]/u);
  assert.match(script, /nothing was sent/u);
  assert.match(script, /function inspectSepoliaExecution\(/u);
  assert.match(script, /SIMULATION ONLY/u);
  assert.match(script, /MINED TRANSACTION/u);
  assert.match(script, /State changes/u);
  assert.match(script, /Connected wallet approval/u);
  assert.match(script, /function renderEvmTrace\(/u);
  assert.match(script, /function flattenTraceFrames\(/u);
  assert.match(script, /function renderTraceWaterfall\(/u);
  assert.match(script, /function renderTraceFrameInspector\(/u);
  assert.match(script, /function renderOpcodeExplorer\(/u);
  assert.match(script, /Call waterfall/u);
  assert.match(script, /Gas distribution/u);
  assert.match(script, /Opcode explorer/u);
  assert.match(script, /Stack, memory, and storage values are intentionally excluded/u);
  assert.match(script, /escapeHtml\(format\(value\)\)/u);
});
