import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import test from "node:test";

const uiRoot = new URL("../ui/", import.meta.url);

test("Wallet Lab browser entrypoint is valid ECMAScript module syntax", () => {
  const script = readFileSync(new URL("app.js", uiRoot), "utf8");
  const result = spawnSync(process.execPath, ["--input-type=module", "--check", "-"], {
    encoding: "utf8",
    input: script
  });

  assert.equal(result.status, 0, result.stderr);
});

test("Wallet Lab presents architecture, network, EVM, and execution evidence without redundant panels", () => {
  const html = readFileSync(new URL("index.html", uiRoot), "utf8");
  const script = readFileSync(new URL("app.js", uiRoot), "utf8");
  const architectureExplorer = readFileSync(new URL("architecture-explorer.mjs", uiRoot), "utf8");
  const styles = readFileSync(new URL("styles.css", uiRoot), "utf8");

  for (const panel of ["architecture", "recovery", "network", "authority", "evm", "privacy", "execution"]) {
    assert.match(html, new RegExp(`id="tab-${panel}"[^>]+role="tab"|role="tab"[^>]+id="tab-${panel}"`, "u"));
    assert.match(html, new RegExp(`id="panel-${panel}"[^>]+role="tabpanel"|role="tabpanel"[^>]+id="panel-${panel}"`, "u"));
  }
  assert.match(html, /<script type="module" src="\/app\.js"><\/script>/u);
  assert.doesNotMatch(html, /<script(?![^>]+src=)/u);
  for (const removed of ["tab-overview", "tab-timeline", "tab-userop", "tab-webauthn"]) assert.doesNotMatch(html, new RegExp(`id="${removed}"`, "u"));
  assert.match(html, /Choose an inspection target/u);
  assert.match(html, /active-deployment-name/u);
  assert.match(html, /metric-result-context/u);
  assert.match(html, /metric-network/u);
  assert.match(html, /metric-checks-context/u);
  assert.match(html, /metric-duration-context/u);
  assert.doesNotMatch(html, /<span>Result<\/span>/u);
  assert.doesNotMatch(html, /<select id="deployment-source"/u);
  assert.match(html, /Local deterministic deployment/u);
  assert.match(html, /Connect Sepolia deployment/u);
  assert.match(html, /sepolia-provider/u);
  assert.match(html, /Loom architecture/u);
  assert.match(html, /Recovery &amp; freeze/u);
  assert.match(html, /id="recovery-flow"/u);
  assert.match(script, /function renderRecoveryLifecycle\(/u);
  assert.match(script, /buildRecoveryLifecycle/u);
  assert.match(script, /class="recovery-graph"/u);
  assert.match(script, /function recoveryEdgeGeometry\(/u);
  assert.doesNotMatch(script, /recovery-node-map/u);
  assert.match(html, /architecture-topbar/u);
  assert.match(html, /architecture-search/u);
  assert.match(html, /architecture-exit/u);
  assert.match(html, /architecture-canvas/u);
  for (const removed of ["account-model-explainer", "contract-dossier", "abi-groups", "architecture-browser", "architecture-summary"]) assert.doesNotMatch(html, new RegExp(removed, "u"));
  assert.match(html, /id="execution-workspace"/u);
  assert.doesNotMatch(html, /DEPLOYED CODE/u);
  assert.doesNotMatch(html, /id="contract-search"/u);
  assert.doesNotMatch(html, /id="contract-list"/u);
  assert.match(html, /graph-zoom-in/u);
  assert.match(html, /graph-reset-view/u);
  assert.match(html, /trace-overlay-toggle/u);
  assert.match(html, /How to read this map/u);
  assert.doesNotMatch(html, /Observed operations/u);
  assert.doesNotMatch(html, /panel-operations/u);
  assert.match(html, /RPC &amp; SDK/u);
  assert.match(html, /id="sdk-boundary-flow"/u);
  assert.match(html, /id="sdk-contract-matrix"/u);
  assert.match(script, /function renderSdkRpcLayer\(/u);
  assert.match(script, /SDK_TO_CHAIN_STAGES/u);
  assert.match(html, /Who allowed or constrained this operation/u);
  assert.match(html, /Who can see what/u);
  assert.match(html, /id="authority-graph"/u);
  assert.match(html, /id="privacy-observer-map"/u);
  assert.match(script, /buildOperationLens/u);
  assert.match(script, /function renderAuthorityView\(/u);
  assert.match(script, /function renderPrivacyView\(/u);
  assert.match(script, /function renderSharedOperationLens\(/u);
  assert.doesNotMatch(html, /<details open[^>]*>\s*<summary>Technical details/u);
  assert.match(script, /function renderNetwork\(/u);
  assert.match(script, /buildArchitectureExplorer/u);
  assert.match(script, /function renderFocusedArchitectureNode\(/u);
  assert.match(script, /function runOutcomeLabel\(/u);
  assert.match(script, /function networkLabel\(/u);
  assert.doesNotMatch(script, /does not include both an implementation and an observed account instance/u);
  assert.match(script, /function renderArchitectureSection\(/u);
  assert.match(script, /function githubSourceUrl\(/u);
  assert.match(script, /source\?\.upstream\?\.repository/u);
  assert.match(script, /github\.com\/\$\{source\.upstream\.repository\}\/blob/u);
  assert.match(script, /function explorerAddressUrl\(/u);
  assert.match(script, /View on Sepolia Blockscout/u);
  assert.match(script, /Local chain address/u);
  assert.match(script, /Open source on GitHub/u);
  assert.match(script, /<details class="dossier-metadata">/u);
  assert.match(script, /Contract metadata/u);
  assert.doesNotMatch(script, /Why runtime code matters/u);
  assert.doesNotMatch(script, /Runtime code commitment/u);
  assert.match(script, /Repository path pinned to the commit recorded by this run/u);
  assert.match(script, /function renderArchitectureFunctionDetail\(/u);
  assert.match(script, /function renderFunctionInteractions\(/u);
  assert.match(script, /Why this function exists/u);
  assert.match(script, /Resolved value/u);
  assert.match(script, /Declared expression/u);
  assert.doesNotMatch(script, /Declared fields/u);
  assert.match(script, /function-purpose/u);
  assert.match(script, /function artifactRevision\(/u);
  assert.match(script, /function captureOpenDetails\(/u);
  assert.match(script, /function restoreOpenDetails\(/u);
  assert.match(script, /if \(revision !== state\.artifactRevision\)/u);
  assert.match(script, /function observedTraceOverlay\(/u);
  assert.match(script, /function renderSourceExcerpt\(/u);
  assert.doesNotMatch(script, /Evidence provenance/u);
  assert.match(script, /function beginGraphInteraction\(/u);
  assert.match(script, /function moveGraphInteraction\(/u);
  assert.match(script, /function focusArchitectureNode\(/u);
  assert.match(script, /interaction\.type === "node"/u);
  assert.match(script, /architecture-focus-object[^\n]+data-contract-id=/u);
  assert.match(script, /closest\("button, a, input, nav, \.focus-content"\)/u);
  assert.doesNotMatch(styles, /animation:\s*architecture-node-in/u);
  assert.match(script, /function connectSepoliaDeployment\(/u);
  assert.match(script, /function showDeploymentWorkspace\(/u);
  assert.match(script, /function renderDeployment\(/u);
  assert.match(script, /function renderExecutionWorkspace\(/u);
  assert.match(script, /defaultExecutionArgument/u);
  assert.match(script, /restore-example-inputs/u);
  assert.match(script, /Deployment- and scenario-aware examples are filled in automatically/u);
  assert.match(html, /data-tab="execution"/u);
  assert.match(html, /id="panel-execution"/u);
  assert.match(html, /id="execution-contract-browser"/u);
  assert.match(script, /function renderExecutionCatalog\(/u);
  assert.match(script, /function renderExecutionJourney\(/u);
  assert.match(script, /function renderExecutionGraph\(/u);
  assert.match(script, /EXECUTION GRAPH/u);
  assert.match(script, /function renderOpcodePhaseFlow\(/u);
  assert.match(script, /EVM PHASE FLOW/u);
  assert.match(script, /Selected call route/u);
  assert.match(script, /function opcodePurpose\(/u);
  assert.match(html, /EXECUTION STUDIO/u);
  assert.match(script, /EVM PROGRAM COUNTER/u);
  assert.match(script, /data-opcode-view="all"/u);
  const functionInspectorSource = script.slice(script.indexOf("function renderFunctionInspector("), script.indexOf("function renderExecutionWorkspace("));
  const executionWorkspaceSource = script.slice(script.indexOf("function renderExecutionWorkspace("), script.indexOf("function traceBigInt("));
  assert.doesNotMatch(functionInspectorSource, /HYPOTHETICAL INPUT/u);
  assert.match(executionWorkspaceSource, /HYPOTHETICAL INPUT/u);
  assert.match(executionWorkspaceSource, /Use deployment-wide evidence first/u);
  assert.match(script, /function renderExecutionTools\(/u);
  assert.match(script, /MINED TRANSACTION ANALYZER/u);
  assert.match(script, /Public RPC presets may omit debug tracing/u);
  assert.match(script, /LOCAL ABI COVERAGE/u);
  assert.match(script, /function renderProbeResult\(/u);
  assert.match(script, /function renderTransactionProvenance\(/u);
  assert.match(script, /function runLocalProbe\(/u);
  assert.match(script, /\/api\/execution\/local\/probe/u);
  assert.match(script, /\/api\/execution\/sepolia\/analyze/u);
  assert.match(script, /function runExecutionSimulation\(/u);
  assert.match(script, /function runLocalExecution\(/u);
  assert.match(script, /function sendSepoliaExecution\(/u);
  assert.match(script, /freshSimulation/u);
  assert.match(script, /from: accounts\[0\]/u);
  assert.match(script, /nothing was sent/u);
  assert.match(script, /function inspectSepoliaExecution\(/u);
  assert.match(html, /id="architecture-transaction-toggle"/u);
  assert.match(html, /id="architecture-transaction-dock"/u);
  assert.match(script, /function renderArchitectureTransactionDock\(/u);
  assert.match(script, /buildTransactionArchitectureJourney/u);
  assert.match(script, /data-open-evm-evidence/u);
  assert.match(script, /currentTrace\(artifact\.events\)\?\.kind !== "transaction-analysis"/u);
  assert.match(architectureExplorer, /Publisher \/ bundler executor/u);
  assert.match(architectureExplorer, /does not prove the service identity/u);
  assert.match(script, /SIMULATION ONLY/u);
  assert.match(script, /MINED TRANSACTION/u);
  assert.match(script, /Unavailable without call trace/u);
  assert.match(script, /Hypothetical state delta/u);
  assert.match(script, /Observed state changes/u);
  assert.match(script, /Connected wallet approval/u);
  assert.match(script, /function renderEvmTrace\(/u);
  assert.match(html, /id="evm-behavior-summary"/u);
  assert.match(script, /function renderEvmBehaviorSummary\(/u);
  assert.match(script, /State access/u);
  assert.match(script, /function flattenTraceFrames\(/u);
  assert.match(script, /function renderTraceWaterfall\(/u);
  assert.match(script, /function renderTraceFrameInspector\(/u);
  assert.match(script, /function renderOpcodeExplorer\(/u);
  assert.match(script, /Call waterfall/u);
  assert.match(script, /Gas distribution/u);
  assert.match(script, /Instruction-level EVM movement/u);
  assert.match(script, /Stack, memory, and raw storage payloads are intentionally excluded/u);
  assert.match(script, /escapeHtml\(format\(value\)\)/u);
});
